### ISSUE TITLE
Column stretch

### ISSUE THREAD

**Issue by lazyb5** [wesbos/TweakDeck#1]
I only really use one timeline column. I would like an userscript that makes it fit the in entire screen. Tweetduck used to do this for me. I have tried to use chatgpt to do this with the new tweetdeck but haven't been able to get it to work.

**Comment by wesbos** [comment]
This script adds classes to each column, so You should be able to to that with this css.

```css
.tweakdeck-column-0 {
    width: 100%;

}

.tweakdeck-column-0 > * > *, .tweakdeck-column-0 > * > * > * {
 width: 100% !important;   
        border: 10px solid red;
}
```
